django_quotes/django_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes_app.urls')),
    path('users/', include('users.urls')),
]

django_quotes/quotes_app/urls.py
from django.urls import path
from . import views

app_name = 'quotes_app'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/<str:author>', views.author, name='author'),
    path('add_quote/', views.quote, name='add_quote'),
    path('add_tag/', views.tag, name='add_tag'),
    path('add_author/', views.add_author, name='add_author'),
    ]

django_quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

django_quotes/quotes_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True, blank=False)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=100)
    description = models.CharField(max_length=5000)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes', blank=False)
    quote = models.CharField(max_length=5000, null=False)

    def __str__(self):
        return f"{self.quote}"

django_quotes/users/models.py
from django.db import models

# Create your models here.

django_quotes/quotes_app/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, ModelMultipleChoiceField

from .models import Tag, Author, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.none())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.none())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all()
        self.fields['tags'].queryset = Tag.objects.all()

django_quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

django_quotes/quotes_app/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Author, Quote


def main(request):
    quotes = Quote.objects.all().order_by('-id')
    paginator = Paginator(quotes, 10)
    return render(request, 'quotes_app/index.html', context={'page_obj': paginator.get_page(request.GET.get('page')), "title": "Quotes"})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes_app:main")
    return render(request, 'quotes_app/add_author.html', {"form": AuthorForm()})


def author(request, author: str):
    return render(request, 'quotes_app/author.html', context={"author": Author.objects.get(fullname=author)})


@login_required
def quote(request):

    if request.method == 'POST':
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.save()
            form.save_m2m()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'quotes_app/add_quote.html', {'form': form})
    return render(request, 'quotes_app/add_quote.html', {"form": QuoteForm()})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'quotes_app/add_tag.html', {'form': form})

    return render(request, 'quotes_app/add_tag.html', {'form': TagForm()})

django_quotes/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.checks import messages
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes_app:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_app:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes_app:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes_app:main')

django_quotes/quotes_app/templates/quotes_app/add_author.html
{% extends "quotes_app/base.html" %}

{% block content %}
<h1>Add author</h1>
<form action="{% url 'quotes_app:add_author' %}" method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Fullname</label>
        {{form.fullname}}
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Born date</label>
        {{form.born_date}}
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div class="mb-3 form-label">
        <label class="form-label">Born location</label>
        {{form.born_location}}
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div class="mb-3 form-label">
        <label class="form-label">description</label>
        {{form.description}}
        <span>{{ form.errors.description }}</span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>
{% endblock %}

django_quotes/quotes_app/templates/quotes_app/add_quote.html
{% extends "quotes_app/base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

django_quotes/quotes_app/templates/quotes_app/add_tag.html
{% extends "quotes_app/base.html" %}

{% block content %}
<form method="POST" action="{% url 'quotes_app:add_tag' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>
{% endblock %}

django_quotes/quotes_app/templates/quotes_app/author.html
{% extends "quotes_app/base.html" %}

{% block title %}{{ author.fullname }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p><strong>Born:</strong>
          <span class="author-born-date">{{ author.born_date }}</span>
          <span class="author-born-location">{{ author.born_location }}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">
            {{ author.description }}
        </div>
    </div>
  </div>
{% endblock %}

django_quotes/quotes_app/templates/quotes_app/base.html
 <!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quotes_app:add_author' %}">Add Author</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quotes_app:add_quote' %}">Add Quote</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quotes_app:add_tag' %}">Add Tag</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">SignUp</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

django_quotes/quotes_app/templates/quotes_app/index.html
{% extends "quotes_app/base.html" %}

{% block title %}Quotes{% endblock %}

{% block content %}
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
    <ul class="list-group quote-list">
                {% for quote in page_obj %}
                <li class="list-group-item quote-item">
                    <div class="quote-text"><i>“{{ quote.quote }}”</i></div>
                    <div class="quote-author">by
                        <a href="{% url 'quotes_app:author' quote.author %}"><b>{{ quote.author }}</b></a>
                    </div>
                    <div class="quote-tags">
                        <small>Tags:</small>
                        {% for tag in quote.tags.all %}
                        <span class="tag-name">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">No quotes found.</li>
                {% endfor %}
            </ul>

</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link">Previous</a>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>
{% endblock %}

django_quotes/users/templates/users/login.html
{% extends "quotes_app/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

django_quotes/users/templates/users/signup.html
{% extends "quotes_app/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}